spring:
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  expiration: 2592000000

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always