package com.altankoc.beuverse_backend.enums;

public enum Department {
    MUHENDISLIK_FAKULTESI,
    TIP_FAKULTESI,
    IKTISADI_IDARI_BILIMLER,
    FEN_FAKULTESI,
    DIS_HEKIMLIGI_FAKULTESI,
    ILAHIYAT_FAKULTESI,
    SAGLIK_BILIMLERI_FAKULTESI,
    ILETISIM_FAKULTESI,
    SPOR_BILIMLARI_FAKULTESI,
    DIGER
}
